### ISSUE TITLE
Admin site with filtering

### ISSUE THREAD

**Issue by sysradium** [bfirsh/django-ordered-model#129]
If I open admin site page on pricegroup page and click up/down link, the request goes to:
`/admin/main/pricegroup/f0cd8f4a-e715-11e6-b3ee-0242ac110009/move-up/?shop__id__exact=93e0f534-c99c-11e5-9475-0242ac110006` 
And is being redirected to: `Location:../../?` which is weird.

Also sometimes `shop__id__exact`  is being set to the wrong PK in 302 redirect.

It seems that it for some reason uses query string from a previous request. So if filter pricegroup by one shop__id, then against another and after that click `move_up` - it will return a redirect to the first shop. Problem appears when you use gunicorn with gevent. Apparently because of this https://github.com/bfirsh/django-ordered-model/blob/master/ordered_model/admin.py#L46

**Comment by shuckc** [comment]
`request_query_string` is used to store URI context between the 'view' generating the changeset (where the request object is available) and rendering the individual move up/down cells in the template (where it is not).  I use gunicorn with 3 _threaded_ workers and have not seen any correctness issues like this. 

Since gunicorn+gevent monkey patches the socket writes so they are non-blocking and uses co-routines, there's scope to begin generating the next changeset before the previous template has finished generating, so all bets are off with this code as it's not designed to be re-entrant. I don't know enough about the unicorn+gevent "threading" model to make it re-entrant, do you know if they patch the `threading.local` API to work? If so we could use that.

**Comment by shuckc** [comment]
I've pushed a tentative fix for this to my own repo - I can now have a filter in the admin page running in two tabs and they don't interfere. Can you try pulling that with pip and see if it fixes your problem?

**Comment by sysradium** [comment]
Will do, thanks a lot

**Comment by sysradium** [comment]
@shuckc awesome. Looks like it fixed the problem. By the way it did not go away once I switched to sync worker in gunicorn.
