### ISSUE TITLE
Migration from Model to OrderedModel

### ISSUE THREAD

**Issue by vmax** [bfirsh/django-ordered-model#139]
If the model (`SomeModel`) you migrate from already had `ordering` set to some field, changing base class to `OrderedModel` (and `OrderedModel.Meta`) would silently prevent ordering from working (as in `SomeModel.objects.all()` still returns instances ordered with respect to that field instead of `order`)

**Comment by shuckc** [comment]
If you already have an ordering field in your model, extend `OrderedModelBase` (rather than `OrderedModel`) and override the `order_field_name` value:     

    class MyModel(OrderedModelBase):
        ...
        order_field_name = "sort_order"

        class Meta:
            ordering = ("sort_order",)

Apologies this is not mentioned in the documentation.
See https://github.com/bfirsh/django-ordered-model/blob/master/ordered_model/models.py#L309

**Comment by vmax** [comment]
@shuckc thank you! I think your PR was supposed to close the issue automatically but didn't for some reason, so closing this manually now.
