### ISSUE TITLE
admin integration when a filter is applied

### ISSUE THREAD

**Issue by dunetna** [bfirsh/django-ordered-model#148]
If I use admin integration and I apply a filter to the list of items, when I click up and down buttons, the selected item may not go up and down because it is moving through the hidden items by the filter. 

It would be nice that if a filter is applied the item would go up or down, jumping all the hidden items.

Thanks!

**Comment by shuckc** [comment]
Hi interesting idea, there is more behaviour that would need to be defined though and as always what seems intuitive to one user might surprise another.
* If I click 'move to top' do I mean make it the first item in the whole collection, or just high enough to be top of the filtered list?
* Likewise with 'move to bottom'
* If I filter the list so there is a single item displayed, what if anything should up/down buttons do? Order with respect to the hidden items or do nothing? 
* Perhaps I want to use the filter simply to find my item quickly to move it relative to all other items, rather than use the filter to express what it should be moved relative to.

I don't think we could really move forward with the suggestion as-is.
